config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  
  resources :podcasts, only: [:index, :show]
  resources :episodes, only: [:index, :show]
  resources :profiles, except: [:new, :create, :destroy]
  resources :reviews
  resources :likes, only: [:create, :show, :destroy]
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :profile
  belongs_to :likeable, polymorphic: true
  validates :profile, uniqueness: {scope: :likeable, message: "only one user like per object"}
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def show
  end

  def create
    @like = Like.create(like_parameters) 
    respond_to do |format|
      if @like.valid?
        @like.save
        format.js
      else
        errors = @like.errors.full_messages
        flash.now[:error] = "#{errors}" 
      end
    end
  end
  
  def destroy
    @like = Like.find_by(like_parameters)
    respond_to do |format|
      @like.destroy!
      format.js
    end
  end

  private
  def like_parameters
    params.require(:like).permit(:profile_id, :likeable_id, :likeable_type)
  end
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/views/likes/_like_button.html.erb
<%= button_to likes_path, 
    remote: true, 
    params: { 
      like: {
        profile_id: profile_id, 
        likeable_id: likeable_id, 
        likeable_type: likeable_type
      } 
    }, 
    form: {id: "like_button" },
    method: :post do %> 

  <%= inline_svg_tag "svg/favorite_outline.svg" %>  
  <p>Add to faves!</p>

<% end %>

app/views/likes/_unlike_button.html.erb
<%= button_to like_path(like_id), 
    remote: true, 
    params: { 
      like: {
        profile_id: profile_id, 
        likeable_id: likeable_id, 
        likeable_type: likeable_type
      } 
    }, 
    form: {id: "like_button" },
    method: :delete do %> 

  <%= inline_svg_tag "svg/favorite.svg" %>  
  <p>Unlike Podcast!</p>

<% end %>

app/views/likes/create.js.erb
var replaced = document.querySelector("#like_button");
replaced.remove();
var review = document.querySelector("#review_button");
review.insertAdjacentHTML('afterend', "<%= j render partial: "likes/unlike_button", locals: {like_id: @like.id, profile_id: current_user.profile.id, likeable_id: @like.likeable.id, likeable_type: @like.likeable.class} %>");

app/views/likes/destroy.js.erb
var replaced = document.querySelector("#like_button");
replaced.remove();
var review = document.querySelector("#review_button");
review.insertAdjacentHTML('afterend', "<%= j render partial: "likes/like_button", locals: {profile_id: current_user.profile.id, likeable_id: @like.likeable.id, likeable_type: @like.likeable.class} %>")