config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "welcome#index"
  
  resources :podcasts, only: [:index, :show]
  resources :episodes, only: [:index, :show]
  resources :profiles, except: [:new, :create, :destroy]
  resources :reviews
  resources :likes, only: [:create, :show, :destroy]
end

app/models/podcast.rb
class Podcast < ApplicationRecord
  self.primary_key = 'id'
  has_many :episodes, dependent: :destroy
  has_many :reviews, dependent: :destroy
  has_many :likes, as: :likeable, dependent: :destroy
  has_many :list_joins, as: :listable, dependent: :destroy
  has_many :lists, through: :list_joins, dependent: :destroy
  validates :rss_feed_link, :title, presence: true
  validates :rss_feed_link, uniqueness: true

  def self.search(query)
    podcasts = Podcast.where("title ILIKE ?", "%#{query}%")
  end

  def avg_rating
    reviews.average("rating")
  end
end

app/controllers/podcasts_controller.rb
class PodcastsController < ApplicationController
  def index
    query = params[:query]
    @query = query if query
    @pagy, @podcasts = pagy Podcast.search(query)

    respond_to do |format|
      format.html
      format.js
      format.json {
        render json: {html: render_to_string(partial: 'podcast-list', locals: {podcasts: @podcasts}, formats: [:html])}
      }
    end

  end

  def show 
    # update and eager load addt'l associations on pcast
    @podcast = Podcast.includes(:reviews).find(params[:id])
    # add addt'l instance variables for addt'l associations
    episode_array = EpisodeBuilder.build_episode(@podcast.rss_feed_link,@podcast.id)
    @episode_pagy, @episodes = pagy_array(episode_array, page_param: :page_episodes)
    @review_pagy, @reviews = pagy(@podcast.reviews, page_param: :page_reviews)
    
    if user_signed_in?
      @profile = current_user.profile
      @review = Review.where(profile: @profile, podcast: @podcast)
    end

    respond_to do |format|
      format.html
      format.js
      format.json {
        render json: {html: render_to_string(partial: 'episodes/episode-list', locals: {episodes: @episodes}, formats: [:html])}
      }
    end

  end

end

app/helpers/podcasts_helper.rb
module PodcastsHelper
end

app/views/podcasts/_podcast-card.html.erb
<div class="podcasts-card__container">
  <%=  link_to podcast_path(podcast)  do %> 
    <%= image_tag(podcast.image_url, alt: podcast.title, class:"podcasts-card__img", size:"120x120", loading: "lazy") %>
  <% end %>
 <div class="podcasts-card__detail">
    <%=  link_to podcast_path(podcast), class: "podcasts-card__title-link" do %> 
      <h4 class="podcasts-card__title"><%= podcast.title %></h4>
    <% end %>
    <div class="podcasts-card__icon-container">
      <%# perhaps put all of this in a separate partial %>
      <div class="podcasts-card__star-icon-group">
      </div>
      <div class="podcasts-card__favorite-icon-group">
      </div>
      <div class="podcasts-card__list-icon-group">
      </div>
      </div>
    <p class="podcasts-card__paragraph">
      <%= podcast.description || podcast.itunes_summary %>
    </p> 
    <div class="podcasts-card__footer">
      <div class="podcasts-card__genre-container">
      <%# render partial 'genres' %>
      </div>
      <div class="podcasts-card__button-container"></div>
      <%# render partial 'buttons' %>
    </div> 
 </div> 
</div>

app/views/podcasts/_podcast-detail.html.erb
<div class="podcast-detail__container">
  <%= link_to podcast.link do %> 
    <%= image_tag(podcast.image_url, alt: podcast.image_title, class:"podcast-detail__img", size:"175x175", loading: "lazy") %>
  <% end %>
  <h1 class="podcast-detail__header">
    <%= podcast.title %>
  </h1>
  <p>
    <%= "by #{podcast.author_name}" %>
  </p>
  <ul class="podcast-detail__genre-list">
  </ul>
  <p class="podcast-detail__description">
    <%= podcast.description %>
  </p>
</div>

app/views/podcasts/_podcast-list.html.erb
  <% podcasts.each do |podcast| %>
    <%= render partial: "podcast-card", locals: {podcast: podcast} %>
  <% end %>

app/views/podcasts/_podcast-nav-tab.html.erb
<div 
  class="podcast-index__container-tab"
  data-tab-target="pane"
  data-controller="paginator"
  data-paginator-current-value="1"
  data-paginator-total-value=<%= paginator.pages %>
  data-paginator-url-value=<%= pagy_url_for(paginator,1) %>>

  <%= yield %>

  <% if paginator.count > Pagy::VARS[:items] %>
    <div class="btn-load-more-container">
      <button 
        class="btn-load-more"
        data-action="click->paginator#paginate" 
        data-paginator-target="button">
          Load More Results!
      </button>
    </div>
  <% end %>
</div>

app/views/podcasts/index.html.erb
<div class="">
  <% if @podcasts.empty? %>
  <h2 class="">Sorry, no results found!</h2>
  <% else %>
  <h2><%= "Search results for: #{@query}" %></h2>
  <p><%= "#{@pagy.count} results found" %></p>
  <% end %>
</div>

<div 
  data-controller="paginator"
  data-paginator-current-value="1"
  data-paginator-total-value=<%= @pagy.pages %>
  data-paginator-url-value=<%= pagy_url_for(@pagy,1) %>>

  <div data-paginator-target="container">
    <%= render partial: "podcast-list", locals: {podcasts: @podcasts} %>
  </div>

  <% if @pagy.count > Pagy::VARS[:items] %>
    <div class="btn-load-more-container">
      <button 
        class="btn-load-more"
        data-action="click->paginator#paginate" 
        data-paginator-target="button">
          Load More Results!
      </button>
    </div>
  <% end %>
</div>

app/views/podcasts/show.html.erb
<div 
  class="podcast-index__container"
  data-controller="tab"
  data-tab-active-class-value="active"
  data-tab-index-value="0">

  <%= render partial: "podcast-detail", locals: {podcast: @podcast} %>

  <ul class="podcast-index__nav-list" >
    <li 
      class="podcast-index__nav-list-item" 
      data-tab-target="tab"
      data-action="click->tab#switch">
      <button class="podcast-index__nav-button" type="button" role="tab">
        Episodes
      </button>        
      <span class="podcast-index__nav-badge"><%= @episode_pagy.count %></span>
    </li>

    <li 
      class="podcast-index__nav-list-item" 
      data-tab-target="tab"
      data-action="click->tab#switch">
      <button class="podcast-index__nav-button" type="button" role="tab">
        Reviews
      </button>        
      <span class="podcast-index__nav-badge"><%= @review_pagy.count %></span> 
    </li>
  </ul>
  
  <div class="podcast-index__container-main">

    <%= render 'podcast-nav-tab', paginator: @episode_pagy do %>
      <div data-paginator-target="container">
      <%= render partial: 'episodes/episode-list', locals: {episodes: @episodes, podcast: @podcast} %>
      </div>
    <% end %>
    
    <%= render 'podcast-nav-tab', paginator: @review_pagy do %>
      <div data-paginator-target="container">
      <%= render partial: 'reviews/review-list', locals: {reviews: @reviews} %>
      </div>
    <% end %>
    
  </div>

  <div class="podcast-index__container-sidebar">
    <div>
      <%= star_rating_helper(@podcast.avg_rating, css_class: "podcast-index__star-icon") %>
    </div>
    <% if user_signed_in? %>
      <% if @review.present? %>
        <%= button_to "Edit a Review!", edit_review_path(@review.first), form: {id: "review_button" },params: {podcast_id: @podcast.id}, method: :get %> 
      <% else %>
        <%= button_to "Leave a Review!", new_review_path, form: {id: "review_button" },params: {podcast_id: @podcast.id}, method: :get %> 
      <% end %>

      <% if current_user.profile.likes_podcast?(@podcast.id) %>
        <%= render partial: "likes/unlike_button", locals: {like_id: current_user.profile.likes.first.id, profile_id: current_user.profile.id, likeable_id: @podcast.id, likeable_type: @podcast.class} %>
      <% else %>
        <%= render partial: "likes/like_button", locals: {profile_id: current_user.profile.id, likeable_id: @podcast.id, likeable_type: @podcast.class} %>
      <% end %>
    <% end %>
  </div>
</div>